OData/WebApi

OData/src/System.Web.OData/OData/ExpressionHelperMethods.cs
OData/src/System.Web.OData/OData/Query/Expressions/SelectExpandBinder.cs
OData/src/System.Web.OData/OData/Query/SelectExpandQueryOption.cs
OData/test/System.Web.OData.Test/OData/Query/Expressions/SelectExpandBinderTest.cs
OData/test/System.Web.OData.Test/OData/SelectExpandTest.cs

Bind $filter in $expand using the expanded property's element type

expand with filter #127

---

OData/src/System.Web.OData/OData/Query/Expressions/SelectExpandBinder.cs
OData/test/System.Web.OData.Test/OData/Query/Expressions/SelectExpandBinderTest.cs

No null propagation for Linq-to-entities.

$filter in $expand throws if Linq-to-entities #251

---

OData/src/System.Web.OData/OData/Query/Expressions/ClrCanonicalFunctions.cs
OData/src/System.Web.OData/OData/Query/Expressions/FilterBinder.cs
OData/test/System.Web.OData.Test/OData/DateTimeTest.cs
OData/test/System.Web.OData.Test/OData/Query/Expressions/FilterBinderTests.cs

Draft datetime $filter and $orderby support

---

_posts/2015-04-17-02-01-model-builder-abstract.md
_posts/2015-04-17-02-02-model-builder-untyped.md
_posts/2015-04-17-02-03-model-builder-nonconvention.md
_posts/2015-04-17-02-04-convention-model-builder.md
_posts/2015-04-17-02-05-model-builder-summary.md

Add the model builder documentation. Thanks for review and merge.

Add model builder documentation

---

CONTRIBUTION.md

Add:
Pass test before pull request.
How to run test case.

Update contribution.md after adding e2e test

---

_posts/2015-04-15-04-11-batch.md

Add the WebAPI Document about Batch

Add the WebAPI Document about Batch

---

OData/test/E2ETest/WebStack.QA.Test.OData/Formatter/Untyped/UntypedDeltaSerializationTests.cs
OData/test/E2ETest/WebStack.QA.Test.OData/QueryComposition/TopSkipOrderByTests.cs
OData/test/E2ETest/WebStack.QA.Test.OData/WebStack.QA.Test.OData.csproj

E2E tests for DeltaToken and Untyped DeltaFeedSerialization

E2E tests for DeltaToken and Untyped DeltaFeedSerialization

---

README.md

Add vNext link to readme

---

_posts/2015-05-12-04-12-batch.md

Add page 'continue-on-error in Batch Request.'

Add page 'continue-on-error in Batch Request.'

---

vNext/NuGet.Config
vNext/samples/ODataSample.Web/Controllers/ProductsController.cs
vNext/samples/ODataSample.Web/Startup.cs
vNext/samples/ODataSample.Web/project.json
vNext/samples/ODataSample.Web/wwwroot/web.config
vNext/src/Microsoft.AspNet.OData/AssemblyProviderManager.cs
vNext/src/Microsoft.AspNet.OData/Common/NotNullAttribute.cs
vNext/src/Microsoft.AspNet.OData/Extensions/BuilderExtensions.cs
vNext/src/Microsoft.AspNet.OData/Extensions/HttpContextExtensions.cs
vNext/src/Microsoft.AspNet.OData/Extensions/HttpRequestExtensions.cs
vNext/src/Microsoft.AspNet.OData/Extensions/ODataServiceCollectionExtensions.cs
vNext/src/Microsoft.AspNet.OData/Formatter/ModernInputFormatter.cs
vNext/src/Microsoft.AspNet.OData/Formatter/Serialization/ODataEntityReferenceLinksSerializer.cs
vNext/src/Microsoft.AspNet.OData/MetadataController.cs
vNext/src/Microsoft.AspNet.OData/ODataOptionsSetup.cs
vNext/src/Microsoft.AspNet.OData/ODataServiceBuilder.cs
vNext/src/Microsoft.AspNet.OData/RequestPreferenceHelpers.cs
vNext/src/Microsoft.AspNet.OData/Routing/Conventions/DefaultODataRoutingConvention.cs
vNext/src/Microsoft.AspNet.OData/Routing/ODataActionSelector.cs
vNext/src/Microsoft.AspNet.OData/Routing/ODataRoute.cs
vNext/src/Microsoft.AspNet.OData/project.json
vNext/test/Microsoft.AspNet.OData.Test/project.json

Only depends on a v3 nuget.org package source.
Add NotNullAttribute
Update xunit runner to 2.1.0
Update using namespaces
Update sample

Build with asp.net 5 beta8

---

OData/packages/repositories.config
OData/test/E2ETestV3/WebStack.QA.Test.OData/Formatter/DeltaEnumTests.cs
OData/test/E2ETestV3/WebStack.QA.Test.OData/WebStack.QA.Test.OData.csproj

For #530 PR, I add some e2e test cases to verify.

Add e2e test cases for enum type in DeltaOfTEntity

---

OData/src/System.Web.OData/OData/Builder/ODataConventionModelBuilder.cs
OData/test/UnitTest/System.Web.OData.Test/OData/Builder/EnumTypeTest.cs

Issue 581: Array of enum doesn't work for convention model builder.

---

vNext/global.json
vNext/samples/ODataSample.Web/Program.cs
vNext/samples/ODataSample.Web/Properties/launchSettings.json
vNext/samples/ODataSample.Web/hosting.json
vNext/samples/ODataSample.Web/project.json
vNext/src/Microsoft.AspNet.OData/Extensions/HttpContextExtensions.cs
vNext/src/Microsoft.AspNet.OData/Extensions/ODataServiceCollectionExtensions.cs
vNext/src/Microsoft.AspNet.OData/ODataOptionsSetup.cs
vNext/src/Microsoft.AspNet.OData/Routing/Conventions/DefaultODataRoutingConvention.cs
vNext/src/Microsoft.AspNet.OData/Routing/ODataActionSelector.cs
vNext/src/Microsoft.AspNet.OData/Routing/ODataRoute.cs
vNext/src/Microsoft.AspNet.OData/Routing/ODataRouteContext.cs
vNext/src/Microsoft.AspNet.OData/project.json
vNext/test/Microsoft.AspNet.OData.Test/project.json

This PR provide changes needed for using odata in ASP.NET MVC 6 RC2

[vNext] Switch to ASP.NET MVC 6 RC2

---

OData/src/System.Web.OData/OData/Query/OrderByNode.cs
OData/src/System.Web.OData/OData/Query/OrderByOpenPropertyNode.cs
OData/src/System.Web.OData/OData/Query/OrderByPropertyNode.cs
OData/src/System.Web.OData/OData/Query/OrderByQueryOption.cs
OData/test/E2ETest/WebStack.QA.Test.OData/QueryComposition/OrderByTests.cs
OData/test/UnitTest/System.Web.OData.Test/OData/Builder/TestModels/Customer.cs
OData/test/UnitTest/System.Web.OData.Test/OData/Query/OrderByPropertyNodeTest.cs
OData/test/UnitTest/System.Web.OData.Test/OData/Query/OrderByQueryOptionTest.cs
OData/test/UnitTest/System.Web.OData.Test/PublicApi/System.Web.OData.PublicApi.bsl
OData/test/UnitTest/System.Web.OData.Test/TestCommon/CustomersModelWithInheritance.cs
OData/test/UnitTest/System.Web.OData.Test/TestCommon/UsefulBuilders.cs

*This pull request fixes issue #630 .*  
Add PropertyPath in OrderByNode to identify duplicate property with different path.

Fix issue #630 orderby with duplicate property

---

OData/test/UnitTest/System.Web.OData.Test/OData/EdmDeltaComplexObjectTest.cs

*Adds missing file for EdmDeltaComplexTypeTests*

Add missing EdmDeltaComplexTypeTests.cs

---

OData/src/System.Web.OData/Extensions/HttpRequestMessageExtensions.cs
OData/src/System.Web.OData/OData/Builder/EdmModelHelperMethods.cs
OData/src/System.Web.OData/OData/ETagMessageHandler.cs
OData/src/System.Web.OData/OData/Formatter/EdmLibHelpers.cs
OData/src/System.Web.OData/OData/Formatter/Serialization/ODataEdmTypeSerializer.cs
OData/src/System.Web.OData/OData/Formatter/Serialization/ODataEntityTypeSerializer.cs
OData/test/E2ETest/WebStack.QA.Test.OData/DeltaQueryTests/DeltaQueryTests.cs
OData/test/E2ETest/WebStack.QA.Test.OData/ETags/ETagsController.cs
OData/test/E2ETest/WebStack.QA.Test.OData/ETags/ETagsModel.cs
OData/test/E2ETest/WebStack.QA.Test.OData/ETags/JsonETagsTests.cs
OData/test/E2ETest/WebStack.QA.Test.OData/ETags/PatchUpdatedEntryWithIfMatchETagsTest.cs

*This pull request fixes issue #926*  
*This pull request fixes issue #927*  
*Fixes writing of ETags on singletons and containment nav props*
*Ensures that null values are written in a delta payload*
*None needed*

Fix writing ETags on singletons and nav props

---

OData/src/System.Web.OData/OData/Formatter/Deserialization/DeserializationHelpers.cs
OData/test/E2ETest/WebStack.QA.Test.OData/Formatter/DeserializationAndSerializationTests.cs
OData/test/E2ETest/WebStack.QA.Test.OData/Formatter/JsonLight/JsonLightDeserializationAndSerializationTests.cs

*This pull request fixes issue #938.*  
*Fixes issue in WebAPI OData when deserializing an untyped string value containing special characters.*
*Once ODataClient is fixed, new test code to test special characters through OData Client in DeserializationAndSerializationTests.cs can be uncommented.*

Untyped data fix

---

OData/src/System.Web.OData/OData/Query/Expressions/SelectExpandBinder.cs
OData/test/E2ETest/WebStack.QA.Test.OData/ETags/DerivedETagTests.cs
OData/test/E2ETest/WebStack.QA.Test.OData/ETags/ETagsController.cs
OData/test/E2ETest/WebStack.QA.Test.OData/ETags/ETagsModel.cs
OData/test/E2ETest/WebStack.QA.Test.OData/WebStack.QA.Test.OData.csproj

*This pull request fixes selects applied against singletons.*  
*None*

Adds support to SelectExpandBinder for etags on singletons and nav props

---

OData/src/System.Web.OData/System.Web.OData.csproj
OData/src/System.Web.OData/packages.config
OData/test/E2ETest/WebStack.QA.Test.OData/WebStack.QA.Test.OData.csproj
OData/test/E2ETest/WebStack.QA.Test.OData/packages.config
OData/test/PerfTest/WebApiPerformance.Service/WebApiPerformance.Service.csproj
OData/test/PerfTest/WebApiPerformance.Service/packages.config
OData/test/UnitTest/Microsoft.TestCommon/Microsoft.TestCommon.csproj
OData/test/UnitTest/Microsoft.TestCommon/packages.config
OData/test/UnitTest/System.Web.OData.Test/System.Web.OData.Test.csproj
OData/test/UnitTest/System.Web.OData.Test/packages.config

Upgrade the ODL dependency to 7.2 version.

Upgrade the ODL dependency to 7.2 version

---

WebApiOData.E2E.msbuild
WebApiOData.Performance.msbuild
WebApiOData.msbuild

Update the msbuild files to make the command line build pass:
1. WebApiOData.E2E.msbuild
2. WebApiOData.Performance.msbuild
3. WebApiOData.Msbuild
Thanks,

Update the msbuild to make the command line build pass

---

README.md

Description
Adding the build badge url for VSTS build for WebApi/master rolling build.
[ ] Test cases added
[ x ] Build and test with one-click build and test script passedAdditional work necessary

Add build badge to show latest build status for WebApi/master branch.

---

README.md

Add build badge for WebApi/maintenance-V4 rolling build on VSTS
[  ] Test cases added
[ x ] Build and test with one-click build and test script passedAdditional work necessary

Add build badge for WebApi/maintenance-V4 rolling build on VSTS

---

src/CommonAssemblyInfo.cs
src/System.Web.OData/Microsoft.AspNet.OData.Nightly.Release.nuspec
src/System.Web.OData/Microsoft.AspNet.OData.Release.nuspec
tools/GetNugetPackageMetadata.proj
tools/WebStack.targets
tools/WebStack.versions.settings.targets

Update NuSpec files for generating Nuget packages.
- Add NuSpec files to build packages
- Add GetNugetPackageMetadata.proj to set build variables to pass to Nuget.exe pack command.
- Add WebStack.versions.settings.targets to control versioning
- Remove company, copyright, version from CommonAssemblyInfo.cs in favor of generated file
from WebStack.versions.settings.targets
A

Update NuSpec files for generating Nuget packages.

---

src/CommonAssemblyInfo.cs
src/System.Web.OData/Microsoft.AspNet.OData.Nightly.Release.nuspec
src/System.Web.OData/Microsoft.AspNet.OData.Release.nuspec
tools/GetNugetPackageMetadata.proj
tools/WebStack.targets
tools/WebStack.versions.settings.targets

Update NuSpec files for generating Nuget packages.
- Add NuSpec files to build packages
- Add GetNugetPackageMetadata.proj to set build variables to pass to Nuget.exe pack command.
- Add WebStack.versions.settings.targets to control versioning
- Remove company, copyright, version from CommonAssemblyInfo.cs in favor of generated file
from WebStack.versions.settings.targets
A

Update NuSpec files for generating Nuget packages. for maintenance-v4

---

README.md

Update nightly feed details in Readme.md

Update nightly feed details.

---

sln/WebApiOData.Performance.Official.sln
test/PerfTest/WebApiPerformance.Service/WebApiPerformance.Service.csproj
tools/perf/PerfRegression.ps1

1. Modify WebApi Performance project to accept the nuget release build
2. Add performance running scripts

Modify WebApi Perf project and add perf scripts

---

test/E2ETestV3/WebStack.QA.Test.OData/ETags/CRUDEntryWithETagsTest.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/Atom/AtomCollectionPropertyTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/Atom/AtomComplexTypeTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/Atom/AtomDeltaTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/Atom/AtomInheritanceTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/Atom/AtomMixScenarioTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/JsonLight/JsonLightCollectionPropertyTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/JsonLight/JsonLightComplexTypeTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/JsonLight/JsonLightDeltaTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/JsonLight/JsonLightInheritanceTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/JsonLight/JsonLightMixScenarioTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Formatter/JsonLight/Metadata/MinimalMetadataSpecificTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/ModelBuilder/SpecialPrimaryKeyTypesInLinkGenerationTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/ODataPathHandler/UnicodeRouteTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/Routing/LinksRoutingConventionTests.cs
test/E2ETestV3/WebStack.QA.Test.OData/StoreGeneratedPattern/StoreGeneratedPatternE2E.cs
test/E2ETestV3/WebStack.QA.Test.OData/Validation/DeltaOfTValidationTests.cs

Comment out a handful of tests that are not passing reliably in the lab. The lab uses a server OS and IIS configuration that works for development does not work in the lab.

Comment out a handful of tests that are not passing reliably in the lab.

---

WebApiOData.E2E.msbuild
WebApiOData.Performance.msbuild
WebApiOData.msbuild
src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSetSerializer.cs
src/Microsoft.AspNet.OData.Shared/Routing/Conventions/AttributeRoutingConvention.cs
src/Microsoft.AspNet.OData.Shared/Routing/Conventions/DynamicPropertyRoutingConvention.cs
src/Microsoft.AspNet.OData.Shared/Routing/Conventions/EntityRoutingConvention.cs
src/Microsoft.AspNet.OData/Adapters/WebApiRequestMessage.cs
src/Microsoft.AspNet.OData/Adapters/WebApiUrlHelper.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Nightly.Release.nuspec
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Release.nuspec
src/Microsoft.AspNet.OData/Routing/Conventions/AttributeRoutingConvention.cs
src/Microsoft.AspNet.OData/Routing/Conventions/MetadataRoutingConvention.cs
src/Microsoft.AspNet.OData/Routing/Conventions/NavigationSourceRoutingConvention.cs
test/UnitTest/Microsoft.Test.AspNet.OData/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.Test.AspNet.OData/Query/Expressions/ModelContainerTest.cs
tools/WebStack.versions.settings.targets

Set version to 7.0.0 alpha.
Fix code analysis/style copy issues.
Update msbuild scripts to 2015.
Update Nuspec files.
Add AspNetCore version of product code

Fix cmdline build, update version to 7.0.0 alpha

---

src/System.Web.OData/OData/Query/Expressions/ClrCanonicalFunctions.cs
src/System.Web.OData/OData/Query/Expressions/ExpressionBinderBase.cs
src/System.Web.OData/OData/Query/Expressions/FilterBinder.cs
test/E2ETest/WebStack.QA.Test.OData/DateTimeOffsetSupport/DateTimeOffsetController.cs
test/E2ETest/WebStack.QA.Test.OData/DateTimeOffsetSupport/DateTimeOffsetDataModel.cs
test/E2ETest/WebStack.QA.Test.OData/DateTimeOffsetSupport/DateTimeOffsetEdmModel.cs
test/E2ETest/WebStack.QA.Test.OData/DateTimeOffsetSupport/DateTimeOffsetTest.cs
test/E2ETest/WebStack.QA.Test.OData/WebStack.QA.Test.OData.csproj
test/UnitTest/System.Web.OData.Test/OData/Query/Expressions/ExpressionStringBuilder.cs
test/UnitTest/System.Web.OData.Test/OData/Query/Expressions/FilterBinderTests.cs

*This pull request fixes issue #1123 
Port Now() support from maintenance-V4 to master.
N/A

Port Now() function from maintenance-V4 to master

---

sln/WebApiOData.AspNetCore.sln
src/CommonAssemblyInfo.cs
src/Microsoft.AspNet.OData.Shared/Formatter/EdmLibHelpers.cs
src/Microsoft.AspNet.OData.Shared/Formatter/EdmPrimitiveHelpers.cs
src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataPrimitiveSerializer.cs
src/Microsoft.AspNet.OData.Shared/Query/Expressions/ExpressionBinderBase.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNetCore.OData/Adapters/WebApiUrlHelper.cs
src/Microsoft.AspNetCore.OData/Formatter/EdmLibHelpers.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataDeltaFeedSerializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataErrorSerializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
src/Microsoft.AspNetCore.OData/NonValidatingParameterBindingAttribute.cs
src/Microsoft.AspNetCore.OData/ODataController.cs
src/Microsoft.AspNetCore.OData/ODataQueryContextExtensions.cs
src/Microsoft.AspNetCore.OData/ODataQueryParameterBindingAttribute.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderBase.cs
src/Microsoft.AspNetCore.OData/ResourceContext.cs
src/Microsoft.AspNetCore.OData/ResourceSetContext.cs
src/Microsoft.AspNetCore.OData/Routing/ODataPathParameterBindingAttribute.cs
tools/WebStack.settings.targets

Initial commit of AspNetCore project in buildable state.
Add AspNetCore version of product code

Initial commit of AspNetCore project in buildable state.

---

test/E2ETest/Common/Database/ConnectionStringBuilder.cs
test/E2ETest/WebStack.QA.Test.OData/Aggregation/AggregationDataModel.cs
test/E2ETest/WebStack.QA.Test.OData/AutoExpand/AutoExpandDataModel.cs
test/E2ETest/WebStack.QA.Test.OData/Cast/CastContext.cs
test/E2ETest/WebStack.QA.Test.OData/DateAndTimeOfDay/DateAndTimeOfDayContext.cs
test/E2ETest/WebStack.QA.Test.OData/DateAndTimeOfDay/DateAndTimeOfDayModel.cs
test/E2ETest/WebStack.QA.Test.OData/DateAndTimeOfDay/DateAndTimeOfDayTest.cs
test/E2ETest/WebStack.QA.Test.OData/DateAndTimeOfDay/DateAndTimeOfDayWithEfTest.cs
test/E2ETest/WebStack.QA.Test.OData/ETags/ETagCurrencyTokenEfContext.cs
test/E2ETest/WebStack.QA.Test.OData/ForeignKey/ForeignKeyContext.cs
test/E2ETest/WebStack.QA.Test.OData/ODataCountTest/CountEdmModel.cs
test/E2ETest/WebStack.QA.Test.OData/QueryComposition/IsOf/IsofDataSource.cs
test/E2ETest/WebStack.QA.Test.OData/QueryComposition/SelectExpandTests.cs
test/E2ETest/WebStack.QA.Test.OData/SingleResult/SingleResultDataModel.cs
test/UnitTest/Microsoft.Test.AspNet.OData.TestCommon/Microsoft.Test.AspNet.OData.TestCommon.csproj
test/UnitTest/Microsoft.Test.AspNet.OData/Routing/Conventions/AttributeRoutingConventionTest.cs

Change from LocalDb V11.0 (VS2013) to MSSQLLocalDB (VS2015).
Add AspNetCore version of product code

Change from LocalDb V11.0 (VS2013) to MSSQLLocalDB (VS2015).

---

src/System.Web.OData/OData/Query/Expressions/FilterBinder.cs
src/System.Web.OData/OData/Query/Expressions/SelectExpandBinder.cs
src/System.Web.OData/OData/Query/ODataQueryOptions.cs
src/System.Web.OData/OData/Routing/Conventions/DynamicPropertyRoutingConvention.cs
src/System.Web.OData/OData/Routing/Conventions/FunctionRoutingConvention.cs

*This pull request fixes issue of WebAPI_master_CodeCoverage build errors introduced in recent merges. Also there probably are some build environment changes recently that has triggered some CA error not detected before. All errors are fixes here.*
*Suppressed CA maintenance warnings. All warnings are triggered by case statements in simple function, and are not recent changes.*

Suppress CA1502 & CA1506.

---

src/Microsoft.AspNetCore.OData/Extensions/ODataRouteBuilderExtensions.cs

*It would be great to have possibility to change a default time zone*

[feature/netcore] Add possibility to change a default time zone

---

README.md

Add feature/netcore branch description
Update build badges
- [ x ] *Build and test with one-click build and test script passed*
Refactor Batching for AspNetCore.
Port Unit Tests to NetCore

Add feature/netcore branch description & build badges

---

src/Microsoft.AspNet.OData/Query/ODataQueryOptions.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs

This pull request fixes #1161 and #1165 
Remove the request from ODataQueryOptions to avoid failing model validation.
Refactor Batching for AspNetCore.
Port Unit Tests to NetCore

Remove the request from ODataQueryOptions to avoid failing model validation

---

_posts/2017-12-21-14-01-netcore-beta1.md

Add notes about #1175.
Update name of Startup.cs file as noted in #975.
Match example URLs to route configuration.

Update release notes for netcore and #1175

---

src/Microsoft.AspNetCore.OData/Formatter/QueryStringMediaTypeMapping.cs

[feature/netcore] Fix error when empty query string

---

src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Nightly.Release.nuspec
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Release.nuspec
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Nightly.Release.nuspec
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Release.nuspec

Point Nuget package licenses to MIT license in WebApi repo.

Point Nuget package licenses to MIT license in WebApi repo.

---

src/Microsoft.AspNet.OData.Shared/Common/SRResources.Designer.cs
src/Microsoft.AspNet.OData.Shared/Common/SRResources.resx
src/Microsoft.AspNet.OData.Shared/IPerRouteContainer.cs
src/Microsoft.AspNet.OData.Shared/PerRouteContainerBase.cs
src/Microsoft.AspNet.OData/PerRouteContainer.cs
src/Microsoft.AspNetCore.OData/Extensions/HttpRequestExtensions.cs
src/Microsoft.AspNetCore.OData/Extensions/ODataRouteBuilderExtensions.cs
src/Microsoft.AspNetCore.OData/PerRouteContainer.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/AttributeRoutingConvention.cs
test/UnitTest/Microsoft.Test.AspNet.OData/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl

This pull request augments the fix for issue #1175
Made per-route services container public since developers may want
to gain access to the container in their own code. This also exposes
two methods for creating OData service containers for using dependency
injection in stand-alone (non-ASP.NET) scenarios.

Improved error message related to per-route services containers.

---

src/Microsoft.AspNetCore.OData/EnableQueryAttribute.cs

If a controller returns a StatusCodeResult object, such as BadRequest(), the result
code of the Result will not be immediately set on the Response object. Therefore,
EnableQueryAttribute need to check both the Response and Result for a success
status code.

Allow EnableQueryAttribute to check for status code on both the response

---

README.md

Add branch entry for maintenance-6.x.

Add branch entry for maintenance-6.x.

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/UnitTest/Microsoft.Test.AspNet.OData/DateTimeTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/EnumSerializerTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/ODataSingletonTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Routing/ODataSingletonRoutingTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/TestControllers.cs

* Issue #939, Test case enabled for ASP.NET Core.
*  Enable ASP.NET Core unit tests for Singleton and DateTime. *

continue on enabling ASP.NET Core unit tests

---

src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataDeltaFeedSerializer.cs
src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/App.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/PerfTest/WebApiPerformance.Service/WebApiPerformance.Service.csproj
test/PerfTest/WebApiPerformance.Service/packages.config
test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/Serialization/ODataDeltaFeedSerializerTests.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Microsoft.Test.AspNet.OData.csproj
test/UnitTest/Microsoft.Test.AspNet.OData/Microsoft.Test.AspNetCore.OData.csproj
test/UnitTest/Microsoft.Test.AspNet.OData/packages.config

* Update to ODL v7.4.1 for all projects.
* Update to ODL v7.4.1 for all projects.
- Classic Product, UT, E2E
- Core Prodct, UT, E2E
- Performance
* Change the Obsolete method call.

Update the ODL reference to v7.4.1 for all projects

---

src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/app.config
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/PerfTest/WebApiPerformance.Service/WebApiPerformance.Service.csproj
test/PerfTest/WebApiPerformance.Service/packages.config
test/UnitTest/Microsoft.Test.AspNet.OData/Microsoft.Test.AspNet.OData.csproj
test/UnitTest/Microsoft.Test.AspNet.OData/Microsoft.Test.AspNetCore.OData.csproj
test/UnitTest/Microsoft.Test.AspNet.OData/packages.config

* Update to ODL 7.4.3
* Update to ODL 7.4.3

Update to ODL 7.4.3 because some failed test cases related to this version

---

test/UnitTest/Microsoft.Test.AspNet.OData/Builder/ContainmentPathBuilderTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/InheritanceTests.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/PrimitiveTypesTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/ODataUriResolverExtensionTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.Test.AspNet.OData/Query/FilterQueryOptionTest.cs

* Fix classic UT failing test cases after update to 7.4.3
* Fix classic UT failing test cases after update to 7.4.3

Fix classic UT failing test cases after update to 7.4.3

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/QueryComposition/TopSkipOrderByTests.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/ODataMediaTypeFormattersTests.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/Serialization/EntityTypeTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
test/UnitTest/Microsoft.Test.AspNet.OData/Routing/ODataRouteTest.cs

* Fix the failing test cases, including the public api
* Fix the failing test cases, including the public api

Fix the failing test cases, including the public api

---

test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/Serialization/EntityTypeTest.cs

* fix the failing classic UT to make VSTS build happy
* fix the failing classic UT to make VSTS build happy

fix the failing classic UT to make VSTS build happy

---

samples/AspNetCoreODataSample.Web/AspNetCoreODataSample.Web.csproj
samples/AspNetCoreODataSample.Web/Controllers/MoviesController.cs
samples/AspNetCoreODataSample.Web/Models/EdmModelBuilder.cs
samples/AspNetCoreODataSample.Web/Models/Genre.cs
samples/AspNetCoreODataSample.Web/Models/Movie.cs
samples/AspNetCoreODataSample.Web/Models/MovieContext.cs
samples/AspNetCoreODataSample.Web/Program.cs
samples/AspNetCoreODataSample.Web/Properties/launchSettings.json
samples/AspNetCoreODataSample.Web/Startup.cs
samples/AspNetCoreODataSample.Web/appsettings.Development.json
samples/AspNetCoreODataSample.Web/appsettings.json
sln/WebApiOData.AspNetCore.sln

* Add a sample project for Asp.NET Core OData
* Add a sample project for Asp.NET Core OData

Add a sample project for Asp.NET Core OData

---

src/Microsoft.AspNetCore.OData/Routing/ODataActionSelector.cs
src/Microsoft.AspNetCore.OData/Routing/ODataPathRouteConstraint.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Routing/ODataRoutingTest.cs
tools/WebStack.versions.settings.targets

* Change the ODataActionSelector and update the ODL version dependency
* Change the ODataActionSelector and update the ODL version dependency

Change the ODataActionSelector and update the ODL version dependency

---

test/UnitTest/Microsoft.Test.AspNet.OData/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl

* update the public api changes in classic
* update the public api changes in classic

update the public api changes in classic

---

src/Microsoft.AspNetCore.OData/Query/QueryFilterProvider.cs

This pull request fixes issue #1329 
Fix QueryFilterProvider by creating a filter item with both
the description and the QueryFilter itself. In AspNetCore,
the description is not enough to filter properly.

Fix QueryFilterProvider() to enable filtering

---

test/E2ETest/WebStack.QA.Test.OData/ETags/JsonETagsTests.cs
test/PerfTest/WebApiPerformance.Service/WebApiPerformance.Service.csproj

*This pull request fixes issue in PR #1225 for perf solution configuration.*
*Edit for perf solution's private build was put in wrong place. Should use notepad to update the dependencies directly instead of using VS.*

Fix Perf solution

---

src/Microsoft.AspNetCore.OData/Extensions/ODataServiceCollectionExtensions.cs
src/Microsoft.AspNetCore.OData/ODataValueProviderFactory.cs

This pull request fixes issue #1337.
Implement ODataValueProviderFactory/ODataValueProvider.

Implement ODataValueProviderFactory/ODataValueProvider.

---

src/Microsoft.AspNetCore.OData/ODataQueryParameterBindingAttribute.cs

This pull request fixes issue #1339.
Modify ODataQueryParameterBinding to ensure that the parameter being bound
is either ODataQueryOptions or ODataQueryOptions<T>.
Earlier versions of WebApi OData did not types derived from ODataQueryOptions or ODataQueryOptions<T> so this behavior is consistent with earlier versions.

Modify ODataQueryParameterBinding to bind ODataQueryOptions.

---

src/Microsoft.AspNetCore.OData/Query/QueryFilterProvider.cs

This pull request fixes issue #1340, #1341.
Modify QueryFilterProvider to skip application of a global query filter
if a filter of the same type is already present in the Filters list.
Modify QueryFilterProvider to apply of a global query filter
if the return type is a Task<> returning a collection and if the
return type is derived from single result.

 Modify QueryFilterProvider to support Async() and scoped EnableQueryAttributes()

---

test/UnitTest/Microsoft.Test.AspNet.Common/AspNetCore/ODataConventionModelBuilderFactory.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Builder/Conventions/Attributes/DataContractAttributeEdmTypeConventionTests.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Builder/Conventions/Attributes/DataMemberAttributeEdmPropertyConventionTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Builder/Conventions/ODataConventionModelBuilderTests.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Builder/ODataConventionModelBuilderHelper.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Microsoft.Test.AspNet.OData.csproj
test/UnitTest/Microsoft.Test.AspNet.OData/Query/OrderByPropertyNodeTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Query/OrderByQueryOptionTest.cs

* Modify to make the model builder test pass
* Modify to make the model builder test pass. 

Modify to make the model builder test pass

---

test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/Serialization/ComplexTypeTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/Serialization/ODataResourceSerializerTests.cs

* Fix the failing ASP.NET Core test cases for serializer
* Fix the failing ASP.NET Core test cases for serializer

Fix the failing ASP.NET Core test cases for serializer

---

src/Microsoft.AspNetCore.OData/ODataQueryParameterBindingAttribute.cs
src/Microsoft.AspNetCore.OData/Routing/ODataActionSelector.cs

*This pull request fixes issue #1365
Modify ODataActionSelector to bind based on available route data taking
into account parameters types the bind using custom binders.

Modify ODataActionSelector to bind based on available route data

---

src/Microsoft.AspNetCore.OData/Extensions/HttpRequestExtensions.cs
src/Microsoft.AspNetCore.OData/Routing/ODataActionSelector.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Query/ApplyQueryOptionTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Routing/Conventions/NavigationSourceRoutingConventionTest.cs

* Make aggregation tests pass and change some product codes
* Make aggregation tests pass and change some product codes

Make aggregation tests pass and change some product codes

---

test/UnitTest/Microsoft.Test.AspNet.Common/AspNet/FormatterTestHelper.cs
test/UnitTest/Microsoft.Test.AspNet.Common/AspNetCore/ODataConventionModelBuilderFactory.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/Serialization/ResourceSetTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Microsoft.Test.AspNet.OData.csproj

* Rename FeedTest to ResourceSetTest and make the test pass
* Rename FeedTest to ResourceSetTest and make the test pass

Rename FeedTest to ResourceSetTest and make the test pass

---

src/Microsoft.AspNet.OData.Shared/Common/Error.cs
src/Microsoft.AspNet.OData.Shared/TypeHelper.cs

* Remove non-used #if NetCore1x
* Remove non-used #if NetCore1x

Remove non-used #if NetCore1x

---

src/Microsoft.AspNetCore.OData/Extensions/ODataApplicationBuilderExtensions.cs
test/UnitTest/Microsoft.Test.AspNet.OData/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

* #1381
* Return IApplicationBuilder for UserODataBatching and update the public api.

Return IApplicationBuilder for UserODataBatching

---

test/UnitTest/Microsoft.Test.AspNet.OData/Routing/ODataLevelsTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/TestControllers.cs

* Make ODataLevelsTests pass
* Make ODataLevelsTests pass

Make ODataLevelsTests pass

---

test/UnitTest/Microsoft.Test.AspNet.Common/AspNet/Microsoft.Test.AspNet.OData.Abstraction.csproj
test/UnitTest/Microsoft.Test.AspNet.Common/AspNet/TestNonODataController.cs
test/UnitTest/Microsoft.Test.AspNet.Common/AspNet/TestODataController.cs
test/UnitTest/Microsoft.Test.AspNet.Common/AspNetCore/TestNonODataController.cs
test/UnitTest/Microsoft.Test.AspNet.Common/AspNetCore/TestODataController.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Microsoft.Test.AspNet.OData.csproj
test/UnitTest/Microsoft.Test.AspNet.OData/Routing/Conventions/NavigationSourceRoutingConventionTest.cs

* Separate TestController to different abstraction
* Separate TestController to different abstraction

Separate TestController to different abstraction

---

test/UnitTest/Microsoft.Test.AspNet.Common/AspNet/FormatterTestHelper.cs
test/UnitTest/Microsoft.Test.AspNet.Common/AspNetCore/FormatterTestHelper.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/PrimitiveTypesTest.cs

* Enable PrimitiveTypeTests
* Enable PrimitiveTypeTests

Enable PrimitiveTypeTests

---

test/UnitTest/Microsoft.Test.AspNet.OData/MetadataControllerTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/OpenComplexTypeTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/OpenEntityTypeTest.cs

* Enable UT for metadata controller and Open entity type
* Enable UT for metadata controller and Open entity type

Enable UT for metadata controller and Open entity type

---

test/UnitTest/Microsoft.Test.AspNet.Common/AspNet/TestNonODataController.cs
test/UnitTest/Microsoft.Test.AspNet.Common/AspNetCore/TestNonODataController.cs
test/UnitTest/Microsoft.Test.AspNet.OData/SelectExpandTest.cs

* Enable SelectExpandTest on Asp.NET Core
* Enable SelectExpandTest on Asp.NET Core

Enable SelectExpandTest on Asp.NET Core

---

README.md

Fix nightly feed links for 7.x.x.

Fix nightly feed links for 7.x.x. in README.md

---

test/UnitTest/Microsoft.Test.AspNet.OData/DependencyInjectionTests.cs
test/UnitTest/Microsoft.Test.AspNet.OData/FunctionActionAdvertisedTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/Query/ODataQueryOptionTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/QueryableLimitationTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/ResourceContextTest.cs
test/UnitTest/Microsoft.Test.AspNet.OData/SelectExpandNestedDollarCountTest.cs

* Enable test cases in Query, selectexpand, etc
* Enable test cases in Query, selectexpand, etc

Enable test cases in Query, selectexpand, etc

---

test/UnitTest/Microsoft.Test.AspNet.Common/AspNet/FormatterTestHelper.cs
test/UnitTest/Microsoft.Test.AspNet.OData/ODataNullValueMessageHandlerTest.cs

* Change some codes to make sure the code analysis pass
* Change some codes to make sure the code analysis pass

Change some codes to make sure the code analysis pass

---

src/Microsoft.AspNet.OData.Shared/Interfaces/IWebApiRequestMessage.cs
src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs
src/Microsoft.AspNet.OData/Adapters/WebApiRequestMessage.cs
src/Microsoft.AspNetCore.OData/Adapters/WebApiRequestMessage.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/QueryComposition/QueryFuzzingTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/ContainmentPathBuilderTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataModelBinderProviderTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/EnableQueryAttributeTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/FilterQueryOptionTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/QueryCompositionTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

*This pull request port WebApi PR https://github.com/OData/WebApi/pull/1225 from maintenance-6.x branch to this new master branch.*
*Changes related to dependency ODL upgrade (7.3.1 -> 7.4.3) from PR #1225 (targeting maintenance-6.x, which was the old master) has been included by PR #1295 into this branch. Therefore only the remaining changes purely related to supporting optionalDollarSign on WebApi is needed for this porting.*

Port optionalDollarSign changes from maintenance-6.x to master branch

---

src/Microsoft.AspNetCore.OData/Batch/ODataBatchHttpRequestMessageExtensions.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchMiddleware.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchPathMapping.cs
src/Microsoft.AspNetCore.OData/Extensions/HttpRequestExtensions.cs
src/Microsoft.AspNetCore.OData/Interfaces/IODataFeature.cs
src/Microsoft.AspNetCore.OData/ODataFeature.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DefaultContainerBuilderTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
test/UnitTest/Microsoft.AspNet.OData.Test/Extensions/HttpRequestExtensions.cs
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNetCore.OData.Test/Batch/ODataBatchPathMappingTest.cs
test/UnitTest/Microsoft.AspNetCore.OData.Test/Extensions/HttpRequestExtensions.cs
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

*This pull request fixes issue https://github.com/OData/WebApi/issues/1386.* It's a feature request.
* Use TemplateMatcher for ODataBatchPathMapping
* Separate the HttpRequestMessageExtensions into different project (classic and core)

Use TemplateMatcher for ODataBatchPathMapping

---

tools/WebStack.versions.settings.targets

* #1059 
* relax the version dependencies for .net core 2.0 package
- [] *Test cases added*

update the DI dependency version

---

src/Microsoft.AspNet.OData.Shared/Formatter/ODataOutputFormatterHelper.cs
src/Microsoft.AspNet.OData.Shared/Routing/DefaultODataPathHandler.cs
src/Microsoft.AspNet.OData.Shared/Routing/ODataPath.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

* #1398.*
* Expose underlying semantic OData path

Expose underlying semantic OData path

---

tools/WebStack.versions.settings.targets

* Update to Beta3
* Update to Beta3

Update to Beta3

---

test/UnitTest/Microsoft.AspNet.OData.Test.Shared/ODataContainmentTest.cs

*This pull request adds test coverage for issue #170.*
*Add tests to ensure issue #170 has been resolved.*

Add test to verify SingleResultWithEmptyIQueryable

---

_posts/2017-12-21-14-01-netcore-beta1.md

update the document for 7.0 beta1

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ModelBuilder/RecursiveComplexTypesE2ETests.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ModelBuilder/RecursiveComplexTypesModels.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/Conventions/ODataConventionModelBuilderTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/RecursiveModel.cs

* Fix the policheck problem
* Fix the policheck problem

Fix the policheck problem

---

.gitignore
samples/AspNetODataSample.Web/App_Start/WebApiConfig.cs
samples/AspNetODataSample.Web/ApplicationInsights.config
samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/Controllers/TodoItemsController.cs
samples/AspNetODataSample.Web/Global.asax
samples/AspNetODataSample.Web/Global.asax.cs
samples/AspNetODataSample.Web/Models/DataSource.cs
samples/AspNetODataSample.Web/Models/EdmModelBuilder.cs
samples/AspNetODataSample.Web/Models/TodoItem.cs
samples/AspNetODataSample.Web/Models/TodoItemContext.cs
samples/AspNetODataSample.Web/Properties/AssemblyInfo.cs
samples/AspNetODataSample.Web/Web.Debug.config
samples/AspNetODataSample.Web/Web.Release.config
samples/AspNetODataSample.Web/Web.config
samples/AspNetODataSample.Web/packages.config
sln/WebApiOData.E2E.AspNet.sln

* add a classic sample project
* add a classic sample project

add a classic sample project

---

.gitignore
_posts/2015-03-20-04-03-filter-in-expand.md
_posts/2015-05-12-04-12-batch.md
_posts/2015-07-24-10-02-work-around-for-singleresult-create.md
_posts/2015-09-16-04-19-odataIncludeAnnotations.md
_posts/2015-09-16-04-20-ContinueOnError.md
_posts/2015-09-17-04-22-Use-HttpRequestMessage-Extension-Method.md
_posts/2016-08-30-13-02-ComplexTypeWithNavigationProperty.md
_posts/2017-12-21-14-01-netcore-beta1.md

*This pull request fixes issue #1485.*
*Updates for GH pages related to HttpConfiguration, HttpRequestMessage, routing conventions, and minor cleanups.*

Misc feature doc updates for 7.0 related to ASP.NET Core.

---

_posts/2018-06-18-12-02-WebApiV7_newDefaultSettings.md

*This pull request fixes section number in PR #1492 (part of issue #1490).*
*Incremented the section number to 12.2.*

Updating section number to 12.2.

---

src/Microsoft.AspNet.OData.Shared/Common/SRResources.resx
src/Microsoft.AspNet.OData/Batch/ODataBatchHttpRequestMessageExtensions.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchHttpRequestMessageExtensions.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Batch/Tests/DataServicesClient/DefaultODataBatchHandlerTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Batch/DefaultODataBatchHandlerTest.cs

*This pull request fixes issue #1503.*
*Add support for application/json media type so that batch processing flow for json format can be initiated.*

Enable support for Json Batch on WebApi layer

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData.Shared/Query/Expressions/AggregationBinder.cs
src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/PerfTest/WebApiPerformance.Service/WebApiPerformance.Service.csproj
test/PerfTest/WebApiPerformance.Service/packages.config
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/DefaultODataPathHandlerTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj

*This pull request updates the ODL dependencies to the newly release v7.5.0.*
*Update dependencies and make tests pass.*

Update ODL dependencies

---

tools/WebStack.versions.settings.targets

* update the version to 7.0 RTM
* update the version to 7.0 RTM

update the version to 7.0 RTM

---

_posts/2018-07-03-04-26-InOperator.md

Adding IN operator feature doc

Adding IN operator feature doc

---

src/Microsoft.AspNet.OData.Shared/Builder/EdmModelHelperMethods.cs
src/Microsoft.AspNet.OData.Shared/Builder/OperationConfiguration.cs
src/Microsoft.AspNet.OData.Shared/Builder/ParameterConfiguration.cs
src/Microsoft.AspNet.OData.Shared/Microsoft.AspNet.OData.Shared.projitems
src/Microsoft.AspNet.OData.Shared/Routing/Conventions/RoutingConventionHelpers.cs
src/Microsoft.AspNet.OData.Shared/Routing/ODataOptionalParameter.cs
src/Microsoft.AspNet.OData.Shared/Routing/ODataRouteConstants.cs
src/Microsoft.AspNetCore.OData/Routing/ODataActionSelector.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BoundOperation/BoundOperationController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BoundOperation/BoundOperationEdmModel.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BoundOperation/BoundOperationTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/ActionConfigurationTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/FunctionConfigurationTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/ODataResourceSetSerializerTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/MetadataControllerTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/AttributeRoutingTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/AttributeRoutingUnboundTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/DefaultODataPathHandlerTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/ODataRoutingModel.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/ODataRoutingTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/TestCommon/CustomersModelWithInheritance.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

* https://github.com/OData/WebApi/issues/1488
* Add the optional parameter into the model builder

Add the optional parameter into the model builder

---

src/Microsoft.AspNet.OData/Batch/ODataBatchContent.cs
src/Microsoft.AspNet.OData/Batch/ODataBatchHttpRequestMessageExtensions.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchContent.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchHttpRequestMessageExtensions.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Batch/Tests/DataServicesClient/DefaultODataBatchHandlerTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

*This pull request fixes issue #1532.*
*Setup the batch response content type based on Accept header in the batch request.*

Fix json batch response content type.

---

samples/AspNetCoreODataSample.Web/Controllers/PeopleController.cs
samples/AspNetCoreODataSample.Web/Models/Person.cs
src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/SelectExpandNode.cs
src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandBinder.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/OpenEntityTypeTest.cs

* #1579 
* Fix the problem when using $select=* can't return the dynamic properties.

Fix $select=* not returning dynamic properties

---

_posts/2015-06-01-10-01-debug-webapi-source.md
_posts/2018-07-03-04-26-InOperator.md

Update docs regarding symbols location

Update docs regarding symbols location

---

samples/AspNetCoreODataSample.Web/Controllers/PeopleController.cs

add comma before **MyLevel** property.

fix compile error

---

src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataEnumDeserializer.cs
src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataPrimitiveDeserializer.cs
src/Microsoft.AspNet.OData.Shared/Routing/Conventions/PropertyRoutingConvention.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceControllers.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceDataModels.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceEdmModels.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceTests.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DateTimeSupport/DateTimeController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DateTimeSupport/DateTimeTest.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Enums/EnumsController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Enums/EnumsTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/ODataDeserializationTestsCommon.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/ODataEnumDeserializerTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/ODataPrimitiveDeserializerTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/SelectExpandNodeTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/Conventions/PropertyRoutingConventionTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/TestCommon/CustomersModelWithInheritance.cs

*This pull request adds a new feature which allows adding new members to a collection of complex types, enums, or primitive types through a POST request.  *
This pull request defines the property routing convention for a POST request on a property and adds end to end testcases for the above-mentioned feature.
Feature documentation needs to be added.

Allow adding new members to a collection through a POST request

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/App.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config

*This pull request fixes issue the security vulnerabilities*
1. Updated the Microsoft.Data.OData to 5.8.4
2. Updated the Microsoft.AspNetCore.All to 2.0.9
3. Updated the Microsoft.AspNetCore.Server.Kestrel.* to 2.0.4

Fix the security vulnerabilities in project dependencies

---

_posts/2018-10-15-12-2-Use-SkipToken-for-Server-Side-Paging.md

Design skip token

---

src/Microsoft.AspNetCore.OData/Extensions/ODataApplicationBuilderExtensions.cs
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

…derExtensions.cs
*This pull request fixes issue #1679 *
Fixes typo in the code

Fix typo in ODataApplicationBuilder.cs

---

samples/AspNetCoreODataSample.Web/Controllers/MoviesController.cs
samples/AspNetCoreODataSample.Web/Models/EdmModelBuilder.cs
samples/AspNetCoreODataSample.Web/Models/Movie.cs
samples/AspNetCoreODataSample.Web/Models/MovieContext.cs
samples/AspNetCoreODataSample.Web/Models/MovieStar.cs
samples/AspNetCoreODataSample.Web/Models/Person.cs
src/Microsoft.AspNet.OData.Shared/Builder/EdmTypeBuilder.cs
src/Microsoft.AspNet.OData.Shared/Builder/NavigationPropertyConfiguration.cs
src/Microsoft.AspNet.OData.Shared/Builder/StructuralTypeConfigurationOfTStructuralType.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/MetadataTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/Company.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/Employee.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/TestCommon/UsefulBuilders.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

* This PR is based on PR: https://github.com/OData/WebApi/pull/1656, with some build failure fix.
* Fix the build failure for PR: https://github.com/OData/WebApi/pull/1656

Allowing the definition of partner relationships

---

tools/WebStack.versions.settings.targets

*This pull request updates release version to 7.1 RTM.*
*version bump to 7.1.*

version bump to 7.1 RTM.

---

_posts/2018-07-18-14-06-webapi-7-1-0.md
_posts/2018-11-19-14-06-webapi-7-1-0.md

*This pull request is for WebAPI 7.1.0 release note.*
*Release note for WebAPI 7.1.0.*

WebAPI release 7.1.0 RTM

---

src/Microsoft.AspNet.OData.Shared/Formatter/ODataModelBinderConverter.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataModelBinderConverterTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems

*This pull request fixes issue #1741 .*
Add any other primitive test cases as needed.

[Regression] Fixes and coverage for primitives in URL parameters.

---

src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs

*This pull request fixes issue #1714.*
*Any expression with contradiction is converted to false.*

Fix for Nav/any(f:false) conversion

---

src/Microsoft.AspNet.OData.Shared/Microsoft.AspNet.OData.Shared.projitems
src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs
src/Microsoft.AspNet.OData.Shared/Query/OrderByCountNode.cs
src/Microsoft.AspNet.OData.Shared/Query/OrderByNode.cs
src/Microsoft.AspNet.OData.Shared/Query/OrderByQueryOption.cs
src/Microsoft.AspNet.OData.Shared/Query/ParameterAliasNodeTranslator.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/FilterQueryOptionTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/OrderByQueryOptionTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

fix issue #194 
This PR based on #738 

Support count in orderby and filter query options

---

_includes/head.html
_layouts/post.html
index.html

adding redirect for content to redirect to https://docs.microsoft.com/odata where the new updated content lives.

adding redirect for content to new docs site

---

src/Microsoft.AspNet.OData.Shared/Builder/Conventions/Attributes/ColumnAttributeEdmPropertyConvention.cs
src/Microsoft.AspNet.OData.Shared/Builder/EdmTypeBuilder.cs
src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ODataOrderByTest/OrderByController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ODataOrderByTest/OrderByDataModel.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ODataOrderByTest/OrderByEdmModel.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ODataOrderByTest/OrderByTest.cs

Reverts OData/WebApi#1762
There are some weird issues with this PR. The build fails because msbuild fails to build the solution even. However, duplicate PR builds fine. Merging the duplicate PR instead.

Revert "Fix ordering the keys according to the ColumnAttribute.Order property"

---

tools/WebStack.versions.settings.targets

*This pull request updates release version to 7.2 RTM.*
*version bump to 7.2.*

Version bump to 7.2.0

---

src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Release.nuspec
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Release.nuspec
tools/WebStack.versions.settings.targets

Update minimum version dependency of ODL to 7.6

Update minimum version of ODL to be 7.6

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Aggregation/AggregationTests.cs

Adding verbose output to fix flakiness in AggregateNavigationPropertyWorks

Added more logging for flacky AggregateNavigationPropertyWorks test

---

tools/WebStack.versions.settings.targets

*This pull request fixes issue #1872.*
*Briefly describe in the https://github.com/OData/odata.net/pull/1553

Change AssemblyVersionAttribute without revision

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData.Shared/Query/Expressions/AggregationBinder.cs
src/Microsoft.AspNet.OData.Shared/Query/Expressions/PropertyContainer.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/SelectExpandNodeTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/SelectExpandTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

* Update to OData Library v7.6.1, fix the failing test cases

Update to OData Library v 7.6.1, fix the failing test cases

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Aggregation/AggregationDataModel.cs

This pull request fixes the failing test cases on the master branch due to a rogue database that existed on the build machines. Now, the database will be recreated if the model changes.

Recreate the DataBase if the Model is detected to be changed.

---

tools/WebStack.versions.settings.targets

Bumps up the version number to 7.2.2

Release 7.2.2 - Bump up the version to 7.2.2

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DollarId/DollarIdClientTest.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DollarId/DollarIdControllers.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DollarId/DollarIdTest.cs

*This pull request fixes parallel running for test cases within "DollarIdTest" and "DollarIdClientTest"

Fix DollarId test parallel running

---

samples/AspNetCore3xEndpointSample.Web/Startup.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchHttpRequestMessageExtensions.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchPathMapping.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs
src/Microsoft.AspNetCore.OData/Extensions/Endpoint/ODataEndpointBuilderExtensions.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Endpoint/EndpointController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Endpoint/EndpointEfCoreTests.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Endpoint/EndpointTestFixture.cs

*This pull request fixes issue https://github.com/OData/WebApi/issues/2068.*
* Enable $batch with Endpoint routing.

Enable $batch request with Endpoint routing

---

src/Microsoft.AspNet.OData/Batch/DefaultODataBatchHandler.cs
src/Microsoft.AspNet.OData/Batch/ODataBatchReaderExtensions.cs
src/Microsoft.AspNet.OData/Batch/ODataBatchResponseItem.cs
src/Microsoft.AspNet.OData/Batch/UnbufferedODataBatchHandler.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchResponseItem.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchStream.cs

*This pull request fixes issue #2009.*
Removed synchronous calls in async batch processing paths.

Fix issue #2009: remove sync calls within async batch processing

---

test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Batch/UnbufferedODataBatchHandlerTest.cs

*This pull request fixes the failing test cases owing the changes in https://github.com/OData/WebApi/pull/2149.*
*Fix the failing test cases

Fix the failing batch async test cases

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
sln/WebApiOData.Performance.Official.sln
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Endpoint/EndpointEfCoreTests.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/NavigationPropertyOnComplexType/SelectImprovementOnComplexTypeTests.cs
test/PerfTest/WebApiPerformance.Service/WebApiPerformance.Service.csproj
test/PerfTest/WebApiPerformance.Service/packages.config
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/SelectExpandNodeTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/FilterQueryOptionTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/Conventions/AttributeRoutingConventionTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

2) Update the release version to 7.5.0
*This pull request fixes issue https://github.com/OData/WebApi/issues/2274.*
1) Update the ODL dependency to 7.7.1
2) Update the Web API release version to 7.5

Update the ODL dependency to ODL 7.7.1 and release version to 7.5

---

src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandBinder.cs
src/Microsoft.AspNet.OData.Shared/Query/HandleNullPropagationOptionHelper.cs

*This pull request fixes issue #2284.*

Continue on the Nullcheck remove fix

---

tools/WebStack.versions.settings.targets

Updates the version number to 7.5.2

Update version to 7.5.2

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/Web.config
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSetSerializer.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/App.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/PerfTest/WebApiPerformance.Service/WebApiPerformance.Service.csproj
test/PerfTest/WebApiPerformance.Service/packages.config
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

Update ODL dependency to 7.7.3.

Update ODL dependency to 7.7.3

---

src/Microsoft.AspNet.OData/Formatter/ODataMediaTypeFormatters.cs
src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatter.cs
src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatterFactory.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Enums/EnumsTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataMediaTypeFormattersTests.cs

Enable JSON Metadata

---

src/Microsoft.AspNet.OData.Shared/Query/Expressions/ExpressionBinderBase.cs
src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs

This pull request fixes issue #2437
Checking IsDate in building binary expression

Filter is not working with date function

---

src/Microsoft.AspNet.OData.Shared/Formatter/ClrTypeCache.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ClrTypeCacheTest.cs

*This pull request fixes issue #2489.*

fix issue #2489: ClrTypeCache has memory leak

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Validators/FilterQueryValidatorTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj

Upgrade ODL version to v7.9.0

---

src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/SelectExpandBinderTest.cs

We added support for $this in ODL https://github.com/OData/odata.net/pull/1998
This PR adds the functionality to WebApi

Add support for $this

---

src/Microsoft.AspNet.OData.Shared/Query/Expressions/ExpressionBinderBase.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs

*This pull request fixes issue #2509 .*

Enable constant parameterization in DateTime constants

---

tools/WebStack.versions.settings.targets

Update version to 7.5.9
7.5.9 Release
- Microsoft.AspNet.OData 7.5.9
- Microsoft.AspNetCore.OData 7.5.9

Update version to 7.5.9

---

.github/CONTRIBUTION.md
License.txt
README.md
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Nightly.nuspec
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Release.nuspec
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Nightly.nuspec
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Release.nuspec

Update copyrights on non source files

Update copyrights on non-source files

---

tools/WebStack.versions.settings.targets

Bump version to 7.5.11

---

src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataResourceDeserializer.cs
src/Microsoft.AspNet.OData/GlobalSuppressions.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceTests.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Formatter/DeltaTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/Conventions/ODataConventionModelBuilderTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/InheritanceModels.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/InheritanceTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl

Fix deltacomplex type

---

src/Microsoft.AspNet.OData.Shared/Common/SRResources.Designer.cs
src/Microsoft.AspNet.OData.Shared/Common/SRResources.resx
src/Microsoft.AspNet.OData.Shared/EnableQueryAttribute.cs
src/Microsoft.AspNet.OData.Shared/Formatter/EdmLibHelpers.cs
src/Microsoft.AspNet.OData.Shared/Microsoft.AspNet.OData.Shared.projitems
src/Microsoft.AspNet.OData.Shared/Query/AutoSelectExpandHelper.cs
src/Microsoft.AspNet.OData.Shared/Query/ExpandModelPath.cs
src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs
src/Microsoft.AspNet.OData.Shared/Query/SelectExpandQueryOption.cs
src/Microsoft.AspNet.OData.Shared/Query/SelectModelPath.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/AutoExpand/AutoExpandNavigationOnComplexTests.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/DeserializationHelpersTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/EnableQueryAttributeTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/ExpandModelPathTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/SelectModelPathTests.cs

Enable Auto expand on complex type

---

src/Microsoft.AspNet.OData.Shared/Query/SelectExpandQueryOption.cs

Fix auto expand null-reference

---

src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
src/Microsoft.AspNet.OData.Shared/EdmChangedObjectCollection.cs
src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataResourceDeserializer.cs
src/Microsoft.AspNet.OData.Shared/NavigationPath.cs
src/Microsoft.AspNet.OData.Shared/ODataAPIHandlerFactory.cs
src/Microsoft.AspNet.OData.Shared/ODataEdmAPIHandlerFactory.cs
src/Microsoft.AspNet.OData.Shared/ODataIdContainer.cs
src/Microsoft.AspNet.OData.Shared/ODataIdResolver.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationControllerEF.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationPatchHandlersEF.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkInsertController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationPatchHandlers.cs

-remove NavigationPath from ODataIdContainer
-make it easy for developer to create a NavigationPath from id/Model
-Add model to APIHandlerFactory base class as a way to provide the model to the methods that require it
-Experiment with setting the id during deserialization in cases where only key values are provided. Should we get this from ODL?
-use the actual path for nested resources in readContext
-rationalize routing odatapath and uriparser odatapath usage
-build out logic/add tests for the path in nested resources for readContext
-should we get the id for key properties during deserialization from ODL?
-handle edge cases throughout
-various other todos as per comments in PR

Draft PR to experiment with refactoring

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/Web.config
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/App.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/DefaultODataPathHandlerTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj

Update ODL version to Latest 7.10 in WebAPi projects
Update ODL version to Latest 7.10 in WebAPi projects

Update ODL version to Latest 7.10 in WebAPi projects

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/OpenType/TypedTest.cs
tools/WebStack.versions.settings.targets

Update WebAPi version for 7.5.13 release
Update WebAPi version for 7.5.13 release

Update WebAPi version for 7.5.13 release

---

tools/WebStack.versions.settings.targets

Update WebStack.versions.settings.targets for release of Webapi 7.5.14

Update WebStack.versions.settings.targets for release of Webapi 7.5.14

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Common/Execution/WebHostTestFixture.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/ODataModelBuilderTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/QueryableLimitationTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj

Update ODL version to v7.11.0

---

src/Microsoft.AspNet.OData.Shared/DefaultContainerBuilder.cs
src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
tools/WebStack.versions.settings.targets

*This pull request fixes https://github.com/OData/AspNetCoreOData/issues/601.*

argument null exception in containerbuilder on .net 6

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

We unlist 7.11.0, so let's update ODL dependency version to 7.11.1.

Update ODL dependency version to 7.11.1

---

src/Microsoft.AspNet.OData.Shared/DeltaSetOfT.cs
src/Microsoft.AspNet.OData.Shared/IODataAPIHandler.cs
src/Microsoft.AspNet.OData.Shared/ODataAPIHandler.cs
src/Microsoft.AspNet.OData.Shared/ODataAPIHandlerFactory.cs
src/Microsoft.AspNet.OData.Shared/ODataAPIResponseStatus.cs

make methods public

---

src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/InheritanceTests.cs

Fix issues in the feature branch

---

src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/InheritanceTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj

Fix reference tags

---

src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj

Fix odl to 7.11.1 in some projects

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

- Updates ODL version to 7.12.2
- Updates release version to 7.5.16

Update release version to 7.5.16 and ODL version to 7.12.2

---

src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/ODataResourceSerializerTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl

* Port the change from 8.x version.

Add virtual method for complex property serialization

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/QueryComposition/ComplextTypeCollectionTests.cs
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj

Bump Microsoft.OWin to 4.0 and Microsoft.AspNetCore.Mvc.Core 2.0.1

---

src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
tools/WebStack.versions.settings.targets

Update version to 7.6.1 and do some clean up

---

tools/WebStack.versions.settings.targets

*This pull request fixes #2719.*

update the version 7.6.2 and update the Core dependency version to 2.0.1

---

src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Aggregation/AggregationController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Aggregation/AggregationDataModel.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Aggregation/AggregationTests.cs

*This pull request fixes #2728.*

Fix serialization issue affecting nested complex property

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

Bump version to 7.6.3 and ODL version to 7.13.0

---

tools/WebStack.versions.settings.targets

Bump version to 7.6.4

---

tools/WebStack.versions.settings.targets

Bump version to 7.6.5

---

src/Microsoft.AspNet.OData.Shared/DefaultODataAPIHandler.cs
src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
src/Microsoft.AspNet.OData.Shared/DeltaSetOfT.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationPatchHandlers.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DeltaSetOfTTest.cs

Fix Handlers on RelatedObjects

---

src/Microsoft.AspNetCore.OData/Results/CreatedODataResult.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/BulkOperation/BulkOperationController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/BulkOperation/BulkOperationTest.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationTest.cs
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl

*This pull request fixes #2754 .*

Make CreatedODataResult inherit from ObjectResult

---

src/Microsoft.AspNet.OData.Shared/Extensions/ContainerBuilderExtensions.cs
src/Microsoft.AspNet.OData.Shared/Microsoft.AspNet.OData.Shared.projitems
src/Microsoft.AspNet.OData.Shared/ODataAPIHandler.cs
src/Microsoft.AspNet.OData.Shared/Query/ExpandQueryBuilder.cs
src/Microsoft.AspNet.OData.Shared/Query/IExpandQueryBuilder.cs
src/Microsoft.AspNet.OData/EnableQueryAttribute.cs
src/Microsoft.AspNet.OData/Extensions/HttpRequestMessageExtensions.cs
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/app.config
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/EnableQueryAttribute.cs
src/Microsoft.AspNetCore.OData/Extensions/HttpRequestExtensions.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/App.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/BulkOperation/BulkOperationEdmModel.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/BulkOperation/BulkOperationTest.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationPatchHandlersEF.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationDataModel.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationEdmModel.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationPatchHandlers.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/ExpandQueryBuilderTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl

Below is how a customer will use the `Deep insert feature`
```csharp
[ODataRoute("Companies")]
[HttpPost]
[EnableQuery]
public ITestActionResult Post([FromBody] Company company)
{
var handler = new CompanyAPIHandler();
handler.ExecuteDeepInsert(company, Request.GetModel(), new APIHandlerFactory(Request.GetModel()));
return Created(company);
}
```
The `EnableQuery` attribute is an action filter. 
We override the `OnActionExecuting` method in AspNetCore and append a `$expand` query string to the `HttpRequest` so that the response could have the navigation properties expand to atleast the level of the request payload.
Same thing happens in the AspNet `EnableQuery` attribute.
We introduce a new `ExpandQueryBuilder` class which Implements `IExpandQueryBuilder` …

Deep insert

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/app.config
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

Update version to v7.7.0 and ODL dependency to v7.16.0

---

src/Microsoft.AspNet.OData.Shared/DefaultODataAPIHandler.cs
src/Microsoft.AspNet.OData.Shared/DeltaSetOfT.cs
src/Microsoft.AspNet.OData.Shared/ODataAPIHandler.cs
src/Microsoft.AspNet.OData.Shared/ODataAPIHandlerFactory.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationControllerEF.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationPatchHandlersEF.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationTestEF.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationPatchHandlers.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DeltaSetOfTTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl

support async method in api handlers

---

src/Microsoft.AspNet.OData.Shared/Query/ExpandQueryBuilder.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationController.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationTest.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/ExpandQueryBuilderTest.cs

Add GenerateExpandQueryStringInternal nullCheck tests

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

Upgrade version to v7.7.1 and update ODL version

---

src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DeltaQueryTests/DeltaQueryTests.cs

*This pull request fixes #2806.*
* Enable write complex dynamic for delta

enable write dynamic complex for delta entity and complex

---

tools/WebStack.versions.settings.targets

Update release version to 7.7.2

---

tools/WebStack.versions.settings.targets

*This pull request fixes #2814.*

Update version to 7.7.3 and relax Asp.NET Package version to >5.2.2 since 5.3.0 was released recently

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/packages.config
src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
src/Microsoft.AspNet.OData/packages.config
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
tools/WebStack.versions.settings.targets

Update version to 7.7.4 and ODL Version

---

tools/WebStack.versions.settings.targets

Update the version to 7.7.5

---

tools/WebStack.versions.settings.targets

Update version to 7.7.6

---

src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/ODataResourceSerializerTests.cs
test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl

Fixes #2858: Add Virtual method for creating Delta response
1) Add a new virtual method to create the ODataNestedResourceInfo for complex and navigation in the delta
2) Add a test to test the calling

Fixes #2858: Add Virtual method for creating Delta response

---

tools/WebStack.versions.settings.targets

Update version to 7.7.7

---

test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/ODataResourceDeserializerTests.cs

Fixes the build error

---

src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/ODataResourceSerializerTests.cs

Fixes #2867: Expand Properties Not Included in Delta Serialization
bug

Fixes #2867: Expand Properties Not Included in Delta Serialization

---

samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
samples/AspNetODataSample.Web/Web.config
samples/AspNetODataSample.Web/packages.config
test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Formatter/JsonLight/Metadata/EntryMetadataTests.cs

This pull request fixes https://github.com/OData/WebApi/security/dependabot/25 by upgrading System.Text.Json dependency from version 8.0.4 (deprecated) to 8.0.5

Upgrade System.Text.Json to mitigate DoS vulnerability

---

samples/AspNetCoreODataSample.Web/AspNetCoreODataSample.Web.csproj
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj

This PR handles multiple known security vulnerabilities by updating or patching affected dependencies. The following CVEs are resolved:
- [CVE-2023-38180](https://github.com/dotnet/announcements/issues/269)
- [CVE-2021-1723](https://github.com/dotnet/announcements/issues/170)
- [CVE-2019-0564](https://github.com/aspnet/Announcements/issues/334)
- [CVE-2020-1045](https://github.com/dotnet/announcements/issues/165)
- [CVE-2024-21907](https://github.com/advisories/GHSA-5crp-9r3c-p9vr)
- [CVE-2024-0056](https://github.com/dotnet/announcements/issues/292)

Fix security vulnerabilities in dependencies

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationController.cs
tools/WebStack.versions.settings.targets

Add a count check in Deep updates E2E tests

Update the version to 7.7.9

---

test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj

Bump `System.Formats.Asn1` version to resolve [CVE-2024-38095](https://www.cve.org/CVERecord?id=CVE-2024-38095)

Resolve CVE-2024-38095 
